### PR TITLE
use turbo-json-parse

### PR DESCRIPTION
**Pull request by mafintosh**
Speeds up the trace event parser by 3-4x, making us >10x faster than a simple JSONStream.parse

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
LGTM

**Review by BridgeAR — APPROVED** [review]
Nice!

**Comment by mafintosh** [comment]
Btw, this shaves off 1.5s on the analysis in bubbleprof on larger profiles

Before:

```
 > time clinic bubbleprof --visualize-only 25547.clinic-bubbleprof
Generated HTML file is 25547.clinic-bubbleprof.html
You can use this command to upload it:
clinic upload 25547.clinic-bubbleprof

real	0m7.297s
user	0m11.234s
sys	0m0.741s
```

After:

```
> time clinic bubbleprof --visualize-only 25547.clinic-bubbleprof
Generated HTML file is 25547.clinic-bubbleprof.html
You can use this command to upload it:
clinic upload 25547.clinic-bubbleprof

real	0m5.867s
user	0m10.205s
sys	0m0.683s
```

Dataset available here, https://upload.clinicjs.org/public/354071a91301ae04e80bdcc1777ec3cad7d441cbeab7befd34e87481a4ee2527/25547.clinic-bubbleprof.html

**Comment by mafintosh** [comment]
1.0.2

**Comment by BridgeAR** [comment]
This seems to break bubbleprof and doctor.

**Comment by mafintosh** [comment]
@BridgeAR yea i noticed that as well last night and pushed a fix then

**Pull request merged**
